[project]
# Basic site settings 
site_name = "Haoze's notes"
site_url = "https://nishchalatattve.github.io/"
site_description = "Notes & references on technology"
site_author = "Haoze Pang and contributors"
copyright = """
Copyright &copy; 2026 The authors.
"""

# Resosetory settings
# repo_url = "https://github.com/nishchalatattve/nishchalatattve.github.io"
# edit_uri = "edit/main/docs/"
# repo_name = "nishchalatattve.github.io"

# nav = []

# Some default settings
docs_dir = "docs"   # This is the default option, included here for clarity.
site_dir = "site"   # This is the default option, included here for clarity.
use_directory_urls = true   # This is the default option, included here for clarity.

# Extra CSS and JS
extra_javascript = [
    "extra-js/mathjax.js",
    "https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js",
    "extra-js/cleanup.js",
]
extra_css = ["stylesheets/extra.css"]
# === Theme ===
[project.theme]
features = [
# Code copy and annotation
    "content.code.annotate",
    "content.code.copy",

# Generate view raw and edit button. Repository must be set (line 11)
    "content.action.edit",
#    "content.action.view",

# Allow user to dismiss announcement banner
    "announce.dismiss",

# Navigation features
    "navigation.tabs",
    "navigation.tabs.sticky",
    "navigation.sections",
    "navigation.expand",
    "navigation.indexes",
#    "navigation.prune",
    "navigation.footer",
    "navigation.path",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.top",   # A back-to-top button can be shown when the user, after scrolling down, starts to scroll up again.
    "navigation.tracking",  # Update URL to the current anchor
    "toc.follow",

# Search features
    "search.highlight",

# Miscelaneous features
    "content.tooltips", # Enable tooltips
    "content.footnote.tooltips",    # Render footnote as tooltips
    "content.tabs.link",    # Generate link for content tabs
]
custom_dir = "overrides"
favicon = "images/lightbulb.png"

language = "en" # Read more at https://zensical.org/docs/setup/language/

# Fonts
font.text = "IBM Plex Serif"
font.code = "Jetbrains Mono"

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.icon]
#logo = "lucide/smile"
repo = "fontawesome/brands/github"

[[project.extra.social]]
icon = "fontawesome/solid/anchor-circle-exclamation"
link = "https://github.com/nishchalatattve/nishchalatattve.github.io/issues"

# Markdown extensions
[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.toc]
permalink = true
toc_depth = 4
[project.markdown_extensions.pymdownx.arithmatex]
generic = true
[project.markdown_extensions.pymdownx.betterem]
smart_enable = "all"
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.emoji]
emoji_generator = "zensical.extensions.emoji.to_svg"
emoji_index = "zensical.extensions.emoji.twemoji"
[project.markdown_extensions.pymdownx.highlight]
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.smartsymbols]
[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
[project.markdown_extensions.pymdownx.tabbed.slugify]
object = "pymdownx.slugs.slugify"
kwds = { case = "lower" }
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true
[project.markdown_extensions.pymdownx.tilde]