[project]
nav = [
    "index.md",
    {"Languages" = [
        "languages/index.md",
        {"Markdown" = [
            "languages/Markdown/index.md"
        ]},
        {"C++" = [
            "languages/C++/index.md",
            "languages/C++/environments.md",
            {"Testing" = [
                "languages/C++/testing/index.md"
            ]},
        ]},
        {"Python" = [
            "languages/Python/index.md"
        ]},
    ]},
    {"Frameworks" = [
        {"Zensical" = [
            "frameworks/zensical_demo/index.md",
            "frameworks/zensical_demo/get_started.md",
            "frameworks/zensical_demo/footnotes.md",
            "frameworks/zensical_demo/tab_groups.md",
            "frameworks/zensical_demo/icons.md"
        ]},
#        {"Toolbox" = []},   # e.g. a PDF extractor. Everything that is not in other folders.
#        {"LLM" = []},
#        {"Scientific computing" = []},
#        {"Web" = []},
    ]} ,
    {"DevOps " = [
        "DevOps/index.md",
        {"Git" = [
            "DevOps/Git/index.md",
            "DevOps/Git/commit-message.md",
        ]}, # Git
        {"GitLab" = [
            "DevOps/GitLab/index.md"
        ]},
        {"Cloud" = [
            "DevOps/cloud/index.md",
            {"Azure" = [
                "DevOps/cloud/Azure/index.md",
            ]},
            {"GCP" = [
                "DevOps/cloud/GCP/index.md"
            ]},
        ]},
        {"Networking" = [
            "DevOps/networking/index.md",
            {"nginx" = [
                "DevOps/networking/nginx/index.md",
                "DevOps/networking/nginx/TLS configuration.md"
            ]},
            {"Tailscale" = []},
            {"NordVPN" = [
                "DevOps/networking/NordVPN/index.md",
            ]}
        ]},
        {"Linux" = [
            "DevOps/Linux/index.md",
        ]},
        {"SSH" = [
            "DevOps/SSH/index.md",
        ]},
#        "DevOps/Terraform/get_started.md",
    ]},
    {"My thoughts" = []},

]

site_name = "Technical Documentation"
site_url = "https://blog.nishchalatattve.com"
site_description = "Various tecnical documentations, including C++, markdown and Python."
site_author = "Haoze Pang"

repo_url = "https://github.com/nishchalatattve/nishchalatattve.github.io"
edit_uri = "edit/main/docs/"
repo_name = "nishchalatattve.github.io"

docs_dir = "docs"   # This is the default option, included here for clarity.
site_dir = "site"   # This is the default option, included here for clarity.
use_directory_urls = true   # This is the default option, included here for clarity.

copyright = """
Copyright &copy; 2026 The authors.
"""

extra_javascript = [
    "javascripts/mathjax.js",
    "https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js"
]

# === Theme ===
[project.theme]
custom_dir = "overrides"
favicon = "images/lightbulb.png"
language = "en" # Read more at https://zensical.org/docs/setup/language/
features = [
    "announce.dismiss",

    "content.action.edit",
#    "content.action.view",

    "content.code.annotate",
    "content.code.copy",

    "content.tooltips",
    "content.footnote.tooltips",

    "content.tabs.link",

#    === Navigation ===
    "navigation.tabs",
    "navigation.tabs.sticky",
    "navigation.sections",
    "navigation.expand",
    "navigation.indexes",
#    "navigation.prune",
    "navigation.footer",
    "navigation.path",

    "navigation.instant",
    "navigation.instant.prefetch",

    "navigation.top",   # A back-to-top button can be shown when the user, after scrolling down, starts to scroll up again.
    "navigation.tracking",  # Update URL to the current anchor


    "search.highlight",

    "toc.follow",
]


font.text = "Inter"
font.code = "Jetbrains Mono"

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.icon]
#logo = "lucide/smile"
repo = "fontawesome/brands/github"

[[project.extra.social]]
icon = "lucide/message-square"
link = "https://github.com/nishchalatattve/nishchalatattve.github.io/discussions/7"

# === Markdown extensions ===
[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.toc]
permalink = true
[project.markdown_extensions.pymdownx.arithmatex]
generic = true
[project.markdown_extensions.pymdownx.betterem]
smart_enable = "all"
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.emoji]
emoji_generator = "zensical.extensions.emoji.to_svg"
emoji_index = "zensical.extensions.emoji.twemoji"
[project.markdown_extensions.pymdownx.highlight]
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.smartsymbols]
[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
[project.markdown_extensions.pymdownx.tabbed.slugify]
object = "pymdownx.slugs.slugify"
kwds = { case = "lower" }
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true
[project.markdown_extensions.pymdownx.tilde]


